cooldowntime: 7
cooldown-message: '&7Slow down there buddy you are still cooling down.'
message: '&b%player%&7 launched &6%click_player% &7into the air!'
world-disabled: '&7You cant launch people in this world.'
sound: 'ENTITY_EXPERIENCE_ORB_PICKUP'
particle: 'MOBSPAWNER_FLAMES'
amount-of-fireworks: 5
flight-time-of-fireworks: 10
launch-power: 5
disabled-worlds:
#- world

